apiVersion: apps/v1
name: CI/CD for Login Form Api Back-end

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/login-form-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/login-form-api:latest


deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure Kubernetes cluster
      run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig
    - name: Deploy to K8s
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml