name: CI/CD for Login Form API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/login-form-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/login-form-api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Start Minikube
        run: minikube start

      - name: Configure Kubernetes cluster
        run: |
          mkdir -p $HOME/.kube
          minikube -p minikube config view --flatten > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f .github/workflows/k8s/deployment.yaml
#          kubectl apply -f .github/workflows/k8s/service.yaml
#          kubectl apply -f .github/workflows/k8s/ingress.yaml
