name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Minikube
        run: |
          sudo apt-get update -y
          sudo apt-get install -y conntrack
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          minikube update-context
          cp -r $(minikube profile list | awk 'NR==2 {print $1}') ~/.kube/config
          echo "KUBE_CONFIG=$HOME/.kube/config" >> $GITHUB_ENV
          echo "Using kubeconfig at: $KUBE_CONFIG"

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Verify Kubernetes Connection
        run: kubectl get nodes --kubeconfig=$KUBE_CONFIG

      - name: Deploy to Minikube
        run: kubectl apply -f .github/workflows/k8s/deployment.yaml --kubeconfig=$KUBE_CONFIG
